import './index.css';
import type { Metadata } from "next";
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import getSession from '@/server_actions/getSession';

export const metadata: Metadata = {
  title: "T2T Digital Logbook",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  const authenticated = (await getSession()).isAuthenticated();
  return (
    <html lang="en">
      <body className="inter-regular-400 h-screen flex flex-col">
        { authenticated && <Header/> }
        <div className='flex-grow px-12'>
          {children}
        </div>
        { authenticated && <Footer/> }
      </body>
    </html>
  );
}
